/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author yapilk
 */
public class dlgAdvanceSearch extends javax.swing.JDialog {

    
    public boolean isTarget = false;
    /**
     * Creates new form dlgAdvanceSearch
     */
    public dlgAdvanceSearch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSrchStatus = new javax.swing.JLabel();
        lblSrchTarget = new javax.swing.JLabel();
        lblSrchOrigin = new javax.swing.JLabel();
        lblSrchWorktype = new javax.swing.JLabel();
        cmbSrchStatus = new javax.swing.JComboBox<>();
        cmbSrchTarget = new javax.swing.JComboBox<>();
        cmbSrchOrigin = new javax.swing.JComboBox<>();
        cmbSrchWorkType = new javax.swing.JComboBox<>();
        btnSrchSearch = new javax.swing.JButton();
        btnSrchClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSrchStatus.setText("Search for Status :");
        lblSrchStatus.setAlignmentX(12.0F);
        lblSrchStatus.setAlignmentY(12.0F);
        getContentPane().add(lblSrchStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, -1, -1));

        lblSrchTarget.setText("Search for Target :");
        getContentPane().add(lblSrchTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 66, -1, -1));

        lblSrchOrigin.setText("Search for Origin :");
        getContentPane().add(lblSrchOrigin, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 109, -1, -1));

        lblSrchWorktype.setText("Search for Work Type :");
        getContentPane().add(lblSrchWorktype, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 155, -1, -1));

        cmbSrchStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "StandBy", "Evaluated", "Done", "OK", "Not OK", "Cancel", "Post Poned" }));
        cmbSrchStatus.setSelectedIndex(-1);
        getContentPane().add(cmbSrchStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 23, 228, -1));

        cmbSrchTarget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSrchTarget.setSelectedIndex(-1);
        getContentPane().add(cmbSrchTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 66, 228, -1));

        cmbSrchOrigin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSrchOrigin.setSelectedIndex(-1);
        getContentPane().add(cmbSrchOrigin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 109, 228, -1));

        cmbSrchWorkType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSrchWorkType.setSelectedIndex(-1);
        getContentPane().add(cmbSrchWorkType, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 152, 229, -1));

        btnSrchSearch.setText("Search");
        btnSrchSearch.setMaximumSize(new java.awt.Dimension(80, 30));
        btnSrchSearch.setMinimumSize(new java.awt.Dimension(80, 30));
        btnSrchSearch.setPreferredSize(new java.awt.Dimension(80, 30));
        btnSrchSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrchSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSrchSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 219, 97, 33));

        btnSrchClose.setText("Close");
        btnSrchClose.setPreferredSize(new java.awt.Dimension(80, 30));
        btnSrchClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrchCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnSrchClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 219, 104, 33));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSrchSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrchSearchActionPerformed
        if(!cmbSrchTarget.equals(null))
        {
            isTarget = true;
        }
        this.dispose();
    }//GEN-LAST:event_btnSrchSearchActionPerformed

    private void btnSrchCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrchCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSrchCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgAdvanceSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgAdvanceSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgAdvanceSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgAdvanceSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgAdvanceSearch dialog = new dlgAdvanceSearch(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSrchClose;
    private javax.swing.JButton btnSrchSearch;
    private javax.swing.JComboBox<String> cmbSrchOrigin;
    private javax.swing.JComboBox<String> cmbSrchStatus;
    private javax.swing.JComboBox<String> cmbSrchTarget;
    private javax.swing.JComboBox<String> cmbSrchWorkType;
    private javax.swing.JLabel lblSrchOrigin;
    private javax.swing.JLabel lblSrchStatus;
    private javax.swing.JLabel lblSrchTarget;
    private javax.swing.JLabel lblSrchWorktype;
    // End of variables declaration//GEN-END:variables
}
